// LOCAL
### GET home
GET http://localhost:3000

### GET all contacts
GET http://localhost:3000/contacts

### GET specific contact
GET http://localhost:3000/contacts/659f0cf2ea5421b2800b9a1b


// PRODUCTION
### GET home
GET https://cse341bh-contacts.onrender.com

### GET all contacts
GET https://cse341bh-contacts.onrender.com/contacts

### GET specific contact
GET https://cse341bh-contacts.onrender.com/contacts/659f0f04ea5421b2800b9a1d
